[build]
publish = "public"
ignore = "false"

[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--no-optional"
# or use low-level NPM_CONFIG_ flag
#NPM_CONFIG_OPTIONAL = "false"
ANTORA_CACHE_DIR = "~+/node_modules/.cache/antora"
ALGOLIA_IDX_NAME = "asciidoctor-docs-replica"

[build.processing]
skip_processing = false

[build.processing.html]
# NOTE must be set to enable forwarding of paths like /asciidoc/latest to /asciidoc/latest/
pretty_urls = true

[build.processing.images]
compress = true

[context.production]
command = """\
npx antora --extension=./docsearch/publish-config-extension.js --fetch --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public ../antora-playbook.yml
"""

[context.production.environment]
ALGOLIA_IDX_NAME = "asciidoctor-docs"

[context.deploy-preview]
# checklinks doesn't understand the DEPLOY_PRIME_URL, so drop it for now
#command = """\
#npx antora --fetch --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public --url $DEPLOY_PRIME_URL ../antora-playbook.yml
#"""
command = """\
npx antora --fetch --html-url-extension-style=indexify --redirect-facility=netlify --to-dir=public ../antora-playbook.yml
"""

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
entryPoints = ["**/*.html"]
recursive = true
pretty = true
skipPatterns = [" href=\"file://"]
todoPatterns = []
checkExternal = false
followSourceMaps = false

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"

# NOTE the following redirects get appended to the redirects defined in the _redirects file

[[redirects]]
from = "https://asciidoctor-docs.netlify.com/*"
to = "https://docs.asciidoctor.org/:splat"
status = 301
force = true

[[redirects]]
from = "/asciidoctor.js"
to = "/asciidoctor.js/latest/"
status = 301
force = true
