name: Retry Deploy Preview
on:
  issue_comment:
    types: [created]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.issue.user.id == github.event.comment.user.id && github.event.comment.body == '/retry'
    steps:
    - name: Retry Deploy Preview
      uses: mojavelinux/retry-netlify-deploy-preview-action@v0.0.2
      with:
        netlify-token: ${{ secrets.NETLIFY_TOKEN }}
        site-id: ${{ secrets.NETLIFY_SITE_ID }}
        pull-request-url: ${{ github.event.issue.pull_request.url }} 
